import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import * as THREE from 'three';
import {SVGRenderer} from 'three/addons/renderers/SVGRenderer.js';
import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';import Lenis from 'lenis';
import {useReviewMode,ReviewControls} from './review-mode.jsx';
import {createSequence,smooth} from './sequence';import './style.css';
gsap.registerPlugin(ScrollTrigger);
function World({p,sequence,reviewProgress}){const host=useThree(s=>s.scene);const camera=useThree(s=>s.camera),invalidate=useThree(s=>s.invalidate);useEffect(()=>{if(reviewProgress!==null){sequence.update(reviewProgress,camera);invalidate()}},[reviewProgress,sequence,camera,invalidate]);useEffect(()=>{sequence.ready.then(invalidate);host.background=sequence.scene.background;host.fog=sequence.scene.fog;},[host,sequence,invalidate]);useFrame(({camera,clock})=>{sequence.update(p.current,camera);if(reviewProgress===null)sequence.animate(clock.elapsedTime)});return <primitive object={sequence.scene}/>}
function GeometryReview({p,sequence}){const root=useRef();useEffect(()=>{const renderer=new SVGRenderer();renderer.setQuality('low');const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);renderer.setSize(innerWidth,innerHeight);root.current.appendChild(renderer.domElement);sequence.scene.traverse(o=>{if(['floor','floor-reflection','atmosphere','constructed-human'].includes(o.name))o.visible=false;if(o.material?.isShaderMaterial)o.material=new THREE.MeshBasicMaterial({color:'#92aaa1'});else if(o.material?.isMeshStandardMaterial)o.material=new THREE.MeshLambertMaterial({color:o.material.color,transparent:o.material.transparent,opacity:o.material.opacity,side:o.material.side})}); // SVGRenderer doesn't support instancing: review positions with lightweight sprites; this is not a WebGL appearance or performance check.
const proxies=[];const pointMaterial=new THREE.SpriteMaterial({color:'#aeb5b1'});
for(let i=0;i<sequence.points.length;i++){const m=new THREE.Sprite(pointMaterial);sequence.scene.add(m);proxies.push([m,i])}sequence.body.visible=false;
let id,lastP=-1;const matrix=new THREE.Matrix4();function frame(){if(Math.abs(p.current-lastP)>1e-6){lastP=p.current;sequence.update(p.current,camera);for(const [m,i]of proxies){sequence.body.getMatrixAt(i,matrix);m.scale.set(0,0,0);matrix.decompose(m.position,m.quaternion,m.scale);m.visible=m.scale.x>.001;m.scale.multiplyScalar(sequence.body.geometry.parameters.width)}renderer.render(sequence.scene,camera);}id=requestAnimationFrame(frame)}frame();const resize=()=>{lastP=-1;renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()};addEventListener('resize',resize);return()=>{cancelAnimationFrame(id);removeEventListener('resize',resize);renderer.domElement.remove()};},[]);return <div className="geometry" ref={root}/>}
function App(){const reviewMode=useReviewMode();const params=new URLSearchParams(location.search);const requestedFrame=Number(params.get('frame'));const frame=params.has('frame')&&(params.get('review')==='geometry'||params.get('inspect')==='1')&&Number.isFinite(requestedFrame)?Math.max(0,Math.min(1,requestedFrame)):null;const p=useRef(reviewMode.enabled?reviewMode.progress:frame??0),root=useRef(),label=useRef(),loading=useRef();const [sequence]=useState(createSequence);const review=new URLSearchParams(location.search).get('review')==='geometry';const [supported]=useState(()=>{if(review)return true;try{const gl=document.createElement('canvas').getContext('webgl2');const available=!!gl;gl?.getExtension('WEBGL_lose_context')?.loseContext();return available}catch{return false}});
useEffect(()=>{
 const sync=q=>{p.current=q;root.current.style.setProperty('--p',q);root.current.style.setProperty('--loading',Math.min(1,q/.96));root.current.style.setProperty('--hero',smooth(.87,.94,q));root.current.style.setProperty('--failure',smooth(.969,.992,q));root.current.style.setProperty('--glitch',smooth(.974,.980,q)*(1-smooth(.984,.993,q)));label.current.textContent=q<.18?'SIGNAL: UNKNOWN':q<.36?'REALITY IS A SIGNAL.':q<.57?'SOURCE: UNVERIFIED':q<.79?'WHAT ARE YOU MADE OF?':'';loading.current.textContent=q>.99?'REALITY FAILED':`LOADING REALITY ${q>=.96?100:Math.round(q*100)}%`;};
 // Exact WebGL review bypasses both Lenis and ScrollTrigger entirely.
 if(reviewMode.enabled){sync(reviewMode.progress);return;}
 const lenis=new Lenis({lerp:.085,smoothWheel:true});const tick=t=>lenis.raf(t*1000);lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);
 const st=ScrollTrigger.create({trigger:'.journey',start:'top top',end:'bottom bottom',onUpdate:s=>sync(frame??s.progress)});sync(frame??st.progress);
 return()=>{gsap.ticker.remove(tick);st.kill();lenis.destroy()};
},[reviewMode.enabled,reviewMode.progress]);
return <main ref={root} className={reviewMode.enabled?"frame-review-mode":undefined}><section className="journey"><div className="stage">{supported?(review?<GeometryReview p={p} sequence={sequence}/>:<Canvas frameloop={reviewMode.enabled?"demand":"always"} camera={{fov:40,near:.1,far:100}} dpr={[1,1.5]} gl={{antialias:true,powerPreference:'high-performance'}}><World p={p} sequence={sequence} reviewProgress={reviewMode.enabled?reviewMode.progress:null}/></Canvas>):<div className="unavailable">WebGL 2 is unavailable in this browser.<br/><a href="?review=geometry">Open geometry review</a></div>}
{review&&<div className="review">GEOMETRY POINT REVIEW · WEBGL / LIGHTING / PERFORMANCE UNVERIFIED</div>}
<div className="journey-label" ref={label}>SIGNAL: UNKNOWN</div><div className="hud"><span>REALITY<br/>IS<br/>OVERRATED</span><div className="title"><b>GLITCH</b><em>REALITY</em></div><div className="claim">NOT EVERYTHING<br/>YOU SEE IS <strong>REAL</strong></div></div><div className="bottom"><span>NOT EVERYTHING IS REAL / 001</span><div className="load-status"><span ref={loading}>LOADING REALITY 0%</span><i className="load-track"/></div></div><div className="scroll">SCROLL TO DECODE <span>↓</span></div><div className="failure"/>{reviewMode.enabled&&<ReviewControls progress={reviewMode.progress} select={reviewMode.select}/>}</div></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
