import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import * as THREE from 'three';
import {SVGRenderer} from 'three/addons/renderers/SVGRenderer.js';
import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';import Lenis from 'lenis';
import {createSequence,smooth} from './sequence';import './style.css';
gsap.registerPlugin(ScrollTrigger);
function World({p,sequence}){const host=useThree(s=>s.scene);useEffect(()=>{host.background=sequence.scene.background;host.fog=sequence.scene.fog;},[host,sequence]);useFrame(({camera})=>sequence.update(p.current,camera));return <primitive object={sequence.scene}/>}
function GeometryReview({p,sequence}){const root=useRef();useEffect(()=>{const renderer=new SVGRenderer();renderer.setQuality('low');const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);renderer.setSize(innerWidth,innerHeight);root.current.appendChild(renderer.domElement);sequence.scene.traverse(o=>{if(o.name==='floor')o.visible=false;if(o.material?.isShaderMaterial)o.material=new THREE.MeshBasicMaterial({color:'#92aaa1'});else if(o.material?.isMeshStandardMaterial)o.material=new THREE.MeshLambertMaterial({color:o.material.color,transparent:o.material.transparent,opacity:o.material.opacity,side:o.material.side})}); // SVGRenderer doesn't support instancing: review a sparse shared-geometry sample.
const proxies=[];for(let i=0;i<sequence.points.length;i+=1){const m=new THREE.Mesh(sequence.body.geometry,new THREE.MeshLambertMaterial({color:'#aeb5b1'}));sequence.scene.add(m);proxies.push([m,i])}sequence.body.visible=false;
let id,lastP=-1;const matrix=new THREE.Matrix4();function frame(){if(Math.abs(p.current-lastP)>1e-6){lastP=p.current;sequence.update(p.current,camera);for(const [m,i]of proxies){sequence.body.getMatrixAt(i,matrix);matrix.decompose(m.position,m.quaternion,m.scale);m.visible=m.scale.x>.001}renderer.render(sequence.scene,camera);}id=requestAnimationFrame(frame)}frame();const resize=()=>{lastP=-1;renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()};addEventListener('resize',resize);return()=>{cancelAnimationFrame(id);removeEventListener('resize',resize);renderer.domElement.remove()};},[]);return <div className="geometry" ref={root}/>}
function App(){const p=useRef(0),root=useRef(),label=useRef(),loading=useRef();const [sequence]=useState(createSequence);const review=new URLSearchParams(location.search).get('review')==='geometry';const [supported]=useState(()=>{if(review)return true;try{const gl=document.createElement('canvas').getContext('webgl2');const available=!!gl;gl?.getExtension('WEBGL_lose_context')?.loseContext();return available}catch{return false}});
useEffect(()=>{const lenis=new Lenis({lerp:.085,smoothWheel:true});const tick=t=>lenis.raf(t*1000);lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);const st=ScrollTrigger.create({trigger:'.journey',start:'top top',end:'bottom bottom',onUpdate:s=>{p.current=s.progress;root.current.style.setProperty('--p',s.progress);root.current.style.setProperty('--hero',smooth(.94,.975,s.progress));root.current.style.setProperty('--failure',smooth(.969,.992,s.progress));root.current.style.setProperty('--glitch',smooth(.974,.980,s.progress)*(1-smooth(.984,.993,s.progress)));label.current.textContent=s.progress<.18?'SIGNAL: UNKNOWN':s.progress<.36?'REALITY IS A SIGNAL.':s.progress<.57?'SOURCE: UNVERIFIED':s.progress<.79?'WHAT ARE YOU MADE OF?':'';loading.current.textContent=s.progress>.99?'REALITY FAILED':`LOADING REALITY ${Math.round(s.progress*100)}%`;}});return()=>{gsap.ticker.remove(tick);st.kill();lenis.destroy()}},[]);
return <main ref={root}><section className="journey"><div className="stage">{supported?(review?<GeometryReview p={p} sequence={sequence}/>:<Canvas camera={{fov:40,near:.1,far:100}} dpr={[1,1.5]} gl={{antialias:true,powerPreference:'high-performance'}}><World p={p} sequence={sequence}/></Canvas>):<div className="unavailable">WebGL 2 is unavailable in this browser.<br/><a href="?review=geometry">Open geometry review</a></div>}
{review&&<div className="review">GEOMETRY REVIEW · LIGHTING / PERFORMANCE NOT REPRESENTATIVE</div>}
<div className="journey-label" ref={label}>SIGNAL: UNKNOWN</div><div className="hud"><span>REALITY IS OVERRATED</span><div className="title"><b>GLITCH</b><em>REALITY</em></div><div className="claim">NOT EVERYTHING<br/>YOU SEE IS REAL</div></div><div className="bottom"><span>NOT EVERYTHING IS REAL / 001</span><span ref={loading}>LOADING REALITY 0%</span></div><div className="scroll">SCROLL TO DECODE <span>↓</span></div><div className="failure"/></div></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
